CREATE DATABASE IF NOT EXISTS crud_simples DEFAULT CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

USE crud_simples;

CREATE TABLE IF NOT EXISTS contatos (
    id INT AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    tel VARCHAR(14) DEFAULT('(00)00000-0000'),
    PRIMARY KEY (id)
);